---
name: Orquesta_DiagnoseModule
pack: kafka
description: "Rule to trigger Orquesta_DiagnoseModule usecase"
enabled: false

trigger:
  type: "kafka.new_message"
  parameters: {}

criteria:
  trigger.topic:
    type: "equals"
    pattern: "ASKDAnsible_Topic_ST2V2"
  trigger.message:
    type: "exists"
    pattern: "summary"

action:
  ref: email.OrquestaDiagnose
  parameters:
    #cmd: "echo {{ trigger.message.attributes[0].attributeName }}: {{ trigger.message.attributes[0].attributeValue }}"
    diagnosedata: "{{trigger.message}}"
