---
name: Orquesta_WorkFlowValidation
pack: kafka
description: "Rule to trigger Orquesta_WorkFlowValidation usecase"
enabled: true

trigger:
  type: "kafka.new_message"
  parameters: {}

criteria:
  trigger.topic:
    type: "equals"
    pattern: "ASKVAnsible_Topic_ST2V2"
  trigger.message:
    type: "exists"
    pattern: "summary"

action:
  ref: email.Orquesta_WorkFlowValidation
  parameters:
    #cmd: "echo {{ trigger.message.attributes[0].attributeName }}: {{ trigger.message.attributes[0].attributeValue }}"
    validatedata: "{{trigger.message}}"
